export function generatedBanner() {
  return '// @generated by oxiquill docgen. Do not edit by hand.\n';
}

export function generatedTomlBanner() {
  return '# @generated by oxiquill docgen. Do not edit by hand.\n';
}
