import {
  hashText,
  stableFingerprint
} from './hashing.mjs';

export function summarizeCells(cells) {
  const rustCells = cells.filter((cell) => cell.language === 'rust');

  return {
    cellCount: cells.length,
    manifestFingerprint: stableFingerprint(cells),
    rustCellCount: rustCells.length,
    rustFingerprint: stableFingerprint(
      rustCells.map((cell) => ({
        crates: cell.crates,
        id: cell.id,
        inputs: cell.inputs,
        source: cell.source
      }))
    )
  };
}

export function shouldBuildWasm({ changeKinds = new Set(), current, force = false, previous }) {
  if (current.rustCellCount === 0) return false;
  if (force || !previous) return true;
  if (changeKinds.has('crate')) return true;
  return previous.rustFingerprint !== current.rustFingerprint;
}

export function createRuntimeVersion(summary) {
  return stableFingerprint({
    readyAt: Date.now(),
    manifest: hashText(summary?.manifestFingerprint ?? ''),
    rust: hashText(summary?.rustFingerprint ?? '')
  });
}

export function generateRuntimeVersionModule(version) {
  return `// @generated by scripts/generate-doc-runtime.mjs. Do not edit by hand.\nexport const runtimeVersion = ${JSON.stringify(version)};\n`;
}
