import { haskellFunctionName, haskellIdentifier, haskellReaderName } from './haskell-identifiers.mjs';

export function generateHaskellMain(haskellCells) {
  const splitCells = haskellCells.map((cell) => ({ cell, source: splitHaskellCellSource(cell) }));
  const pragmas = uniqueSorted(splitCells.flatMap(({ source }) => source.pragmas));
  const imports = uniqueSorted(splitCells.flatMap(({ source }) => source.imports));
  const cells = splitCells.map(({ cell, source }) => generateHaskellFunction(cell, source.body)).join('\n\n');

  return [
    '-- @generated by oxiquill docgen. Do not edit by hand.',
    ...pragmas,
    'module Main (main) where',
    '',
    'import System.Environment (getArgs)',
    'import Text.Read (readMaybe)',
    ...imports,
    '',
    'main :: IO ()',
    'main = do',
    '  args <- getArgs',
    '  case args of',
    '    cellId : inputValues -> runCell cellId inputValues',
    '    [] -> fail "Expected a Haskell cell id argument."',
    '',
    'runCell :: String -> [String] -> IO ()',
    generateHaskellDispatch(haskellCells),
    '',
    haskellReaders(),
    cells ? `\n${cells}\n` : ''
  ].join('\n');
}

export function generateHaskellFunction(cell, source = splitHaskellCellSource(cell).body) {
  assertSupportedHaskellSource(cell.source, cell);

  const name = haskellFunctionName(cell.id);
  const inputPattern = cell.inputs.map((input) => `raw_${haskellIdentifier(input.name)}`);
  const inputBindings = cell.inputs
    .map((input) => {
      const variable = haskellIdentifier(input.name);
      return `    ${variable} <- ${haskellReaderName(input)} ${haskellStringLiteral(input.name)} raw_${variable}`;
    })
    .join('\n');
  const expectedInputMessage = `Haskell cell ${haskellStringLiteral(cell.id)} expected ${cell.inputs.length} input(s), received `;
  const body = indentHaskellSource(source, '    ');

  if (cell.inputs.length === 0) {
    return `${name} :: [String] -> IO ()
${name} [] = do
${body}
${name} __inputs =
  fail (${haskellStringLiteral(expectedInputMessage)} <> show (length __inputs))`;
  }

  return `${name} :: [String] -> IO ()
${name} __inputs = case __inputs of
  [${inputPattern.join(', ')}] -> do
${inputBindings}
${body}
  _ ->
    fail (${haskellStringLiteral(expectedInputMessage)} <> show (length __inputs))`;
}

export function splitHaskellCellSource(cellOrSource) {
  const source = typeof cellOrSource === 'string' ? cellOrSource : cellOrSource.source;
  const cell = typeof cellOrSource === 'string' ? undefined : cellOrSource;
  assertSupportedHaskellSource(source, cell);

  const pragmas = [];
  const imports = [];
  const body = [];
  let isPreamble = true;

  for (const line of source.split('\n')) {
    const trimmed = line.trim();

    if (isPreamble && trimmed === '') continue;
    if (isPreamble && /^--(?!\|)/u.test(trimmed)) continue;
    if (isPreamble && /^\{-#\s+LANGUAGE\b/u.test(trimmed)) {
      pragmas.push(trimmed);
      continue;
    }
    if (isPreamble && /^import\s+/u.test(trimmed)) {
      imports.push(trimmed);
      continue;
    }

    isPreamble = false;
    body.push(line);
  }

  return {
    body: body.join('\n').trim(),
    imports,
    pragmas
  };
}

export function generateHaskellInputBinding(input) {
  const variable = haskellIdentifier(input.name);
  return `${variable} <- ${haskellReaderName(input)} ${haskellStringLiteral(input.name)} raw_${variable}`;
}

function generateHaskellDispatch(haskellCells) {
  if (haskellCells.length === 0) {
    return 'runCell cellId _ = fail ("unknown Haskell cell: " <> cellId)';
  }

  const cases = haskellCells
    .map((cell) => `  ${haskellStringLiteral(cell.id)} -> ${haskellFunctionName(cell.id)} inputValues`)
    .join('\n');

  return `runCell cellId inputValues = case cellId of
${cases}
  _ -> fail ("unknown Haskell cell: " <> cellId)`;
}

function haskellReaders() {
  return `readDoubleInput :: String -> String -> IO Double
readDoubleInput name raw = case readMaybe raw of
  Just value -> pure value
  Nothing -> fail ("input " <> show name <> " must be a number, received " <> show raw)

readIntInput :: String -> String -> IO Int
readIntInput name raw = case readMaybe raw of
  Just value -> pure value
  Nothing -> fail ("input " <> show name <> " must be an integer, received " <> show raw)

readBoolInput :: String -> String -> IO Bool
readBoolInput _ "true" = pure True
readBoolInput _ "false" = pure False
readBoolInput name raw = fail ("input " <> show name <> " must be a boolean, received " <> show raw)

readStringInput :: String -> String -> IO String
readStringInput _ raw = pure raw`;
}

function assertSupportedHaskellSource(source, cell) {
  const moduleMatch = source.match(/^\s*module\s+\S+\s+where\b/mu);
  if (!moduleMatch) return;

  const context = cell ? ` "${cell.id}" in ${cell.pagePath}` : '';
  throw new Error(`Haskell cell${context} cannot declare a module; write a snippet body instead.`);
}

function haskellStringLiteral(value) {
  return `"${String(value)
    .replace(/\\/gu, '\\\\')
    .replace(/"/gu, '\\"')
    .replace(/\n/gu, '\\n')
    .replace(/\r/gu, '\\r')
    .replace(/\t/gu, '\\t')}"`;
}

function indentHaskellSource(source, prefix) {
  const trimmed = source.trim();
  if (!trimmed) return `${prefix}pure ()`;

  return trimmed
    .split('\n')
    .map((line) => `${prefix}${line}`)
    .join('\n');
}

function uniqueSorted(values) {
  return Array.from(new Set(values)).sort();
}
