import { hashText, stableFingerprint } from './hashing.mjs';

export function summarizeCells(cells) {
  const rustCells = cells.filter((cell) => cell.language === 'rust');
  const pythonCells = cells.filter((cell) => cell.language === 'python');
  const haskellCells = cells.filter((cell) => cell.language === 'haskell');

  return {
    cellCount: cells.length,
    haskellCellCount: haskellCells.length,
    haskellFingerprint: stableFingerprint(
      haskellCells.map((cell) => ({
        id: cell.id,
        inputs: cell.inputs,
        source: cell.source
      }))
    ),
    manifestFingerprint: stableFingerprint(cells),
    pythonCellCount: pythonCells.length,
    pythonFingerprint: stableFingerprint(
      pythonCells.map((cell) => ({
        id: cell.id,
        packages: cell.packages,
        source: cell.source
      }))
    ),
    rustCellCount: rustCells.length,
    rustFingerprint: stableFingerprint(
      rustCells.map((cell) => ({
        crates: cell.crates,
        id: cell.id,
        inputs: cell.inputs,
        source: cell.source
      }))
    )
  };
}

export function shouldBuildWasm({ changeKinds = new Set(), current, force = false, previous }) {
  if (current.rustCellCount === 0) return false;
  if (force || !previous) return true;
  if (changeKinds.has('crate')) return true;
  return previous.rustFingerprint !== current.rustFingerprint;
}

export function shouldBuildHaskellWasm({ current, force = false, previous }) {
  if (current.haskellCellCount === 0) return false;
  if (force || !previous) return true;
  return previous.haskellFingerprint !== current.haskellFingerprint;
}

export function createRuntimeVersion(summary) {
  return stableFingerprint({
    haskell: hashText(summary?.haskellFingerprint ?? ''),
    manifest: hashText(summary?.manifestFingerprint ?? ''),
    rust: hashText(summary?.rustFingerprint ?? '')
  });
}

export function generateRuntimeVersionModule(version) {
  return `// @generated by oxiquill docgen. Do not edit by hand.\nexport const runtimeVersion = ${JSON.stringify(version)};\n`;
}
